wandb_version: 1

n_proc:
  desc: null
  value: 42
min_inference_size:
  desc: null
  value: 38
timestep_limit:
  desc: null
  value: 50000000000
exp_buffer_size:
  desc: null
  value: 150000
ts_per_iteration:
  desc: null
  value: 50000
standardize_returns:
  desc: null
  value: true
standardize_obs:
  desc: null
  value: false
policy_layer_sizes:
  desc: null
  value:
  - 1024
  - 1024
  - 512
  - 512
critic_layer_sizes:
  desc: null
  value:
  - 1024
  - 1024
  - 512
  - 512
ppo_epochs:
  desc: null
  value: 2
ppo_batch_size:
  desc: null
  value: 50000
ppo_minibatch_size:
  desc: null
  value: 50000
ppo_ent_coef:
  desc: null
  value: 0.005
ppo_clip_range:
  desc: null
  value: 0.2
gae_lambda:
  desc: null
  value: 0.95
gae_gamma:
  desc: null
  value: 0.99
policy_lr:
  desc: null
  value: 0.0003
critic_lr:
  desc: null
  value: 0.0003
shm_buffer_size:
  desc: null
  value: 8192
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714063767.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 5
      - 14
      - 16
      - 23
      - 62
      4: 3.9.19
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
